#!/usr/bin/env php
<?php
require_once 'vendor/autoload.php';
require_once 'load.php';
def_return('bu\aux\match', (!isset($argv[1])) ? '/.*/iu' : '/'.$argv[1].'/iu');

def_sprintfer('in_green', "\033[32m%s\033[0m");

foreach(docs() as $k=>$v){
        if($t = ob(function() use($v){
                foreach($v['fns'] as $kk=>$vv)
                        if(preg_match(bu\aux\match(), $kk))
                                echo '   '.in_green($kk).":\n"."      ".
                                     implode("\n      ", explode("\n", trim($vv)))."\n\n";
        })){
                echo in_green($k);
                if($it = $v['doc'])
                        echo " - ".$it;
                echo "\n";
                echo $t;
        }
}
